spring.application.name=user-service

# ---- Server ----
server.port=8081

# ---- Database connection (pg-users container) ----
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/usersdb}
spring.datasource.username=lakshmiskitchen
spring.datasource.password=devpassword

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- Actuator ----
management.endpoints.web.exposure.include=health,info,prometheus