spring.application.name=payment-service

# ---- Server ----
server.port=8084

# ---- Database connection (pg-payments container) ----
spring.datasource.url=jdbc:postgresql://localhost:5436/paymentsdb
spring.datasource.username=lakshmiskitchen
spring.datasource.password=devpassword

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- Other services ----
order.service.url=http://localhost:8083

# ---- Actuator ----
management.endpoints.web.exposure.include=health,info,prometheus