spring.application.name=order-service

# ---- Server ----
server.port=8083

# ---- Database connection (pg-orders container) ----
spring.datasource.url=jdbc:postgresql://localhost:5435/ordersdb
spring.datasource.username=lakshmiskitchen
spring.datasource.password=devpassword

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- Other services ----
menu.service.url=http://localhost:8082
# ---- Actuator ----
management.endpoints.web.exposure.include=health,info,beans,prometheus

